export const personalInfo = {
  name: "Carlos García",
  location: "Alicante, España",
  email: "carlos@hackwithcarlos.com",
  role: "Security Operations Center (SOC) Analyst",
  github: "https://github.com/Timmy842",
  linkedin: "https://www.linkedin.com/in/carlos-garcia-durendez/",
  description: "¡Hola! Soy Carlos, un apasionado de la ciberseguridad con especial interés en pentesting, análisis forense y seguridad en redes. Me dedico a investigar y desarrollar herramientas de seguridad para identificar vulnerabilidades y fortalecer sistemas. En mi tiempo libre, realizo CTFs y experimentos prácticos para mejorar mis habilidades en hacking ético, pruebas de intrusión y mitigación de amenazas. Además, me gusta compartir conocimientos y colaborar en proyectos que contribuyan a un ecosistema digital más seguro. Siempre estoy en busca de nuevos retos y oportunidades para seguir creciendo en el mundo de la ciberseguridad. 🚀",
};

export const workExperience = [
  {
    company: "Resistenias Industriales Maxiwatt S.L.",
    location: "Alicante, Comunidad Valenciana, España - Hibrido",
    position: "PHP Backend Developer",
    period: "Mayo 2025 - Actualidad",
    achievements: [
      "Desarrollo y mantenimiento de aplicaciones web utilizando PHP (Laravel) en el backend.",
      "Participación en tareas de frontend con Angular, asegurando una integración fluida con las APIs backend.",
      "Colaboración en la documentación técnica de los proyectos para facilitar su mantenimiento y escalabilidad.",
      "Subida a servidor y despliegue de aplicaciones en entornos de producción en momentos clave del desarrollo.",
      "Tareas de mantenimiento correctivo y evolutivo, incluyendo resolución de incidencias críticas.",
      "Soporte en el mantenimiento de hardware, garantizando el correcto funcionamiento de los equipos y sistemas informáticos."
    ],
  },
  {
    company: "Lynx View",
    location: "Alicante, Comunidad Valenciana, España - Hibrido",
    position: "Full-stack Developer",
    period: "Marzo 2024 - Octubre 2024",
    achievements: [
      "Toma de decisiones en el frontend utilizando tecnologías como Angular y React.",
      "Trabajo en el backend con Laravel y Node.js, asegurando una arquitectura robusta y escalable.",
      "Creación de documentación técnica de las aplicaciones desarrolladas.",
      "Resolución de incidencias de procesos críticos que puedan afectar al correcto funcionamiento del resto de sistemas."
    ],
  },
  {
    company: "Gestión Tributaria Territorial",
    location: "Alicante, Comunidad Valenciana, España - Hibrido",
    position: "Full-stack Developer",
    period: "Septiembre 2023 - Marzo 2024",
    achievements: [
      "Implementación de soluciones frontend con Angular y Vue.",
      "Desarrollo de microservicios backend utilizando Node.js y PHP/Laravel, asegurando la integridad de los procesos.",
      "Trabajo con bases de datos relacionales y optimización del diseño de consultas SQL.",
      "Soporte a la creación de documentación técnica de las aplicaciones desarrolladas.",
      "Resolución de incidencias de procesos críticos que puedan afectar al correcto funcionamiento del resto de sistemas."
    ],
  },
  {
    company: "Sprinter",
    location: "Alicante, Comunidad Valenciana, España - Hibrido",
    position: "Aplication Maintenance Development",
    period: "Marzo 2022 - Septiembre 2023",
    achievements: [
      "Procesos de integración con herramientas TALEND para ETL, DQ, ESB, .NET.",
      "Procesos backend y microservicios en Java y Node.js.",
      "Desarrollo de nuevos proyectos en Cloud (Google Cloud Platform, Java).",
      "Trabajo con bases de datos relacionales y no relacionales (MongoDB, ElasticSearch, Redis) y optimización del diseño de consultas SQL.",
      "Soporte a la creación de documentación técnica de las aplicaciones desarrolladas.",
      "Resolución de incidencias de procesos críticos que puedan afectar al correcto funcionamiento del resto de sistemas."
    ],
  },
];

export const education = [
  {
    institution: "IES San Vicente",
    location: "Alicante, Comunidad Valenciana, España",
    degree: "Curso de Especialización en Ciberseguridad en Entornos de las Tecnologías de la Información",
    period: "Septiembre 2024 - Junio 2025",
    achievements: [
      "Incidentes de ciberseguridad",
      "Análisis forense informático",
      "Bastionado de redes y sistemas",
      "Puesta en producción segura",
      "Hacking ético",
      "Normativa de ciberseguridad",
      "Análisis de tráfico de red con Wireshark para detectar amenazas.",
      "Realización de pruebas de penetración en entornos controlados utilizando Metasploit.",
      "Investigación forense en sistemas Windows y Linux con Autopsy y Volatility.",
      "Configuración de servidores seguros mediante hardening y monitorización de logs.",
      "Automatización de auditorías de seguridad con scripts en Python y Bash.",
      "Aplicación de normativas de ciberseguridad en entornos empresariales."
    ],
  },
  {
    institution: "IG Formacion",
    location: "Alicante, Comunidad Valenciana, España",
    degree: "Ciclo Formativo de Grado Superior en Desarrollo de Aplicaciones Web",
    period: "Septiembre 2020 - Junio 2022",
    achievements: [
      "Desarrollo web en entorno cliente (JavaScript, AJAX)",
      "Desarrollo web en entorno servidor (PHP, Node.js, Laravel)",
      "Bases de datos (SQL, MySQL, PostgreSQL)",
      "Despliegue de aplicaciones web (Docker, servidores)",
      "Diseño de interfaces web (HTML, CSS, Bootstrap)",
      "Seguridad y accesibilidad en aplicaciones web",
      "Desarrollo de aplicaciones full-stack con PHP, Laravel y Node.js",
      "Implementación de bases de datos relacionales optimizadas",
      "Creación de APIs RESTful y consumo de APIs externas",
      "Diseño de interfaces responsivas con HTML, CSS y Bootstrap",
      "Configuración y administración de servidores para despliegue",
      "Optimización del rendimiento y seguridad en aplicaciones web"
    ],
  },
];
export const skills = {
  cibersecurityGlobal: [
    "Ciberseguridad",
    "Evaluación de vulnerabilidades y pruebas de penetración (VAPT)",
    "Análisis forense digital",
    "Seguridad de redes",
    "Hacking ético",
    "Desarrollo de software",
    "Seguridad en la nube",
    "Gestión de identidades y accesos (IAM)",
    "Normativas y estándares de seguridad (ISO 27001, GDPR, PCI DSS)",
  ],
  redTeam: [
    "Kali Linux",
    "Metasploit",
    "Burp Suite",
    "Wireshark",
    "Nmap",
    "Nikto",
    "OWASP ZAP",
    "John the Ripper",
    "Hydra",
    "Aircrack-ng",
    "Snort",
    "Zeek",
    "Ettercap",
    "Netcat",
    "Maltego",
    "MISP",
    "Yara",
    "Volatility",
    "Autopsy",
    "FTK Imager",
    "Suricata",
    "Cuckoo Sandbox",
    "RATs (Remote Access Trojans)",
    "Shodan",
    "CVE (Common Vulnerabilities and Exposures)",
    "MITRE ATT&CK",
    "Exploit DB",
    "Elastic Stack (ELK)",
    "OWASP Top 10",
    "Proxychains",
    "Tor",
    "DNS Spoofing",
    "ARP Spoofing",
    "XSS (Cross-Site Scripting)",
    "CSRF (Cross-Site Request Forgery)",
    "SQL Injection",
    "Privilege Escalation",
    "Buffer Overflow",
    "Reverse Engineering",
  ],
  blueTeam: [
    "Splunk",
    "ELK Stack (Elasticsearch, Logstash, Kibana)",
    "SIEM (Security Information and Event Management)",
    "IDS/IPS (Intrusion Detection/Prevention Systems)",
    "Firewalls",
    "Antivirus/EDR solutions",
    "Incident response",
    "Threat hunting",
    "Vulnerability management",
    "Security awareness training",
    "Network segmentation",
    "Data loss prevention (DLP)",
    "Endpoint protection",
    "Security policies and procedures",
  ],
  frontendDevelopment: [
    "React.js",
    "Vue.js",
    "Angular",
    "HTML5",
    "CSS3",
    "JavaScript",
    "TypeScript",
    "Tailwind CSS",
    "Bootstrap",
    "Redux",
    "jQuery",
    "Next.js",
    "API Consumption (REST/GraphQL)",
    "PWA (Progressive Web Apps)",
    "Axios",
    "Vite",
    "Postman",
    "Git"
  ],
  backendDevelopment: [
    "Node.js",
    "Express.js",
    "Nest.js",
    "PHP",
    "Laravel",
    "Java",
    "Spring Boot",
    "Python",
    "Django",
    "Flask",
    "Ruby on Rails",
    "GraphQL",
    "RESTful APIs",
    "Microservices architecture",
    "Docker",
    "Kubernetes",
    "Redis",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "SQLite",
  ],
  databaseAndStorage: [
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Firebase",
    "SQLite",
    "ElasticSearch",
    "AWS S3",
    "Google Cloud Storage",
  ],
  toolsAndServices: [
    "Git",
    "GitHub",
    "GitLab",
    "Jira",
    "Trello",
    "Slack",
    "Zoom",
    "Figma",
    "Postman",
    "Docker",
    "Kubernetes",
    "AWS (Amazon Web Services)",
    "Google Cloud Platform (GCP)",
    "Microsoft Azure",
    "Sentry",
  ],
};

export const projects = [
  {
    title: "Port Scanner",
    github: "https://github.com/Timmy842/port-scanner",
    tags: ["Python", "Sockets", "Threading", "Security"],
    category: "security",
    description: [
      "Herramienta de reconocimiento de red desarrollada en Python que identifica puertos abiertos en una máquina objetivo de forma eficiente.",
      "Implementa sockets TCP/UDP para detección precisa de servicios activos.",
      "Soporte para rangos de puertos personalizados y modo verbose.",
      "Multithreading para escaneos paralelos con mayor rendimiento.",
    ],
  },
  {
    title: "Network Traffic Analyzer",
    github: "https://github.com/Timmy842",
    tags: ["Python", "Scapy", "Wireshark", "PCAP"],
    category: "security",
    description: [
      "Analizador de tráfico de red basado en Python con Scapy para captura e inspección de paquetes en tiempo real.",
      "Detecta patrones sospechosos como escaneos, ARP Spoofing y conexiones anómalas.",
      "Genera informes en formato PCAP compatibles con Wireshark.",
      "Filtra por protocolo (TCP/UDP/ICMP), IP de origen/destino y puertos.",
    ],
  },
  {
    title: "Vulnerability Scanner",
    github: "https://github.com/Timmy842",
    tags: ["Python", "Nmap", "CVE", "Automation"],
    category: "security",
    description: [
      "Script de automatización de auditorías de seguridad que integra Nmap y APIs de CVE para evaluar vulnerabilidades.",
      "Identifica servicios desactualizados y los cruza con bases de datos de vulnerabilidades conocidas.",
      "Genera reportes detallados con nivel de criticidad (CVSS) y recomendaciones de mitigación.",
      "Integración con la API de NVD (National Vulnerability Database).",
    ],
  },
  {
    title: "Grind SkateShop",
    github: "https://github.com/Timmy842/grind-skateshop",
    tags: ["PHP", "Laravel", "JavaScript", "Tailwind CSS"],
    category: "dev",
    description: [
      "Tienda online de material de skate con carrito de compra, gestión de inventario y panel de administración.",
      "Backend con PHP y Laravel: autenticación, sesiones seguras, y API RESTful.",
      "Frontend dinámico con JavaScript y AJAX para experiencia sin recargas.",
      "Estilizado con Tailwind CSS, diseño completamente responsive.",
    ],
  },
];

export const ctfPlatforms = [
  {
    name: "HackTheBox",
    username: "TimmyPwn3d",
    profileUrl: "https://app.hackthebox.com/users/865586",
    icon: "htb",
    stats: "Active member | Machines & Challenges",
    color: "green",
  },
  {
    name: "TryHackMe",
    username: "TimmyPwn3d",
    profileUrl: "https://tryhackme.com/p/TimmyPwn3d",
    icon: "thm",
    stats: "Active member | Learning Paths completed",
    color: "red",
  },
];

export const certRoadmap = [
  { name: "SEC1 Security Fundamentals", status: "target", issuer: "TryHackMe" },
  { name: "eJPT (eLearnSecurity Junior Penetration Tester)", status: "target", issuer: "INE Security" },
  { name: "CRTA (Certified Red Team Analyst)", status: "goal", issuer: "Cyber Warfare Labs" },
];

export const awards = [
  {
    name: "Cyber Security 101 Learning Path",
    institution: "TryHackMe",
    date: "March 2026",
    credentialUrl: "https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-THSGSPNZ8O.pdf",
    category: "security",
    skills: [
      "Linux",
      "Networking",
      "Web Security",
      "Cryptography",
      "Defensive Security",
      "Offensive Security",
      "SOC",
      "Threat Intelligence",
    ],
  },
  {
    name: "Pre Security Learning Path",
    institution: "TryHackMe",
    date: "March 2026",
    credentialUrl: "https://tryhackme.com/certificate/THM-ASNOMZVSYW",
    category: "security",
    skills: [
      "Networking",
      "Linux",
      "Windows",
      "Web Fundamentals",
      "How The Web Works",
    ],
  },
  {
    name: "Curso completo de Hacking Ético y Ciberseguridad",
    institution: "Udemy",
    date: "December 2024",
    credentialUrl: "https://www.udemy.com/certificate/UC-4974c5d7-8aab-488f-89b3-82ca1f999eb7",
    category: "security",
    skills: [
      "Shodan",
      "Maltego",
      "Wireshark",
      "Nmap",
      "Nessus",
      "Metasploit",
      "Burp Suite",
      "SQL Injection",
      "Path Traversal",
      "WebShells",
      "Unrestricted File Upload",
      "Cross-Site-Scripting",
      "CSRF",
      "XSStrike",
      "Command Injection",
      "MITM",
      "ARP Spoofing",
      "DNS Spoofing",
      "Polymorph",
      "Meterpreter",
      "UAC Bypass",
      "Cracking Passwords",
      "Backdoors",
      "Evidence Cleanup"
    ]
  },
  {
    name: "React: De cero a experto ( Hooks y MERN )",
    institution: "Udemy",
    date: "August 2022",
    credentialUrl: "https://www.udemy.com/certificate/UC-fa59fdf5-93b0-44ee-8601-173e90720ad4",
    category: "dev",
    skills: [
      "NPM",
      "React Hooks",
      "MERN",
      "React.js"
    ]
  },
  {
    name: "Node: De cero a experto",
    institution: "Udemy",
    date: "July 2022",
    credentialUrl: "https://www.udemy.com/certificate/UC-819996c3-c183-4bc3-8854-14a9200df567",
    category: "dev",
    skills: [
      "NPM",
      "Express.js",
      "Node.js"
    ]
  }
];
